
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package calichescript;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 2;
  public static final int L_KEY = 46;
  public static final int OPSUM = 41;
  public static final int OPCOND = 36;
  public static final int OPGREATER = 32;
  public static final int OUTPUT = 24;
  public static final int OPLESS = 34;
  public static final int INPUT = 23;
  public static final int CASE = 26;
  public static final int INTEGER = 10;
  public static final int R_PAR = 51;
  public static final int FOR = 16;
  public static final int OPCOMP = 30;
  public static final int CHARACTER = 11;
  public static final int SEMICOLON = 53;
  public static final int OPASIGN = 43;
  public static final int OPTION = 27;
  public static final int COMMA = 52;
  public static final int UPTO = 4;
  public static final int R_KEY = 47;
  public static final int NUM = 3;
  public static final int IF = 13;
  public static final int ID = 29;
  public static final int CONSTSTRING = 9;
  public static final int R_BRACKET = 49;
  public static final int EOF = 0;
  public static final int BOOLEAN = 12;
  public static final int RETURN = 17;
  public static final int OPAND = 38;
  public static final int OPOR = 37;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int NULL = 22;
  public static final int OPASIGNADD = 44;
  public static final int OPINC = 42;
  public static final int BREAK = 21;
  public static final int VOID = 18;
  public static final int SWITCH = 25;
  public static final int COLON = 54;
  public static final int ELSE = 14;
  public static final int VARIABLE = 7;
  public static final int WHILE = 15;
  public static final int DEFAULT = 28;
  public static final int OPDIF = 31;
  public static final int OPMOD = 39;
  public static final int OPLESSEQ = 35;
  public static final int L_PAR = 50;
  public static final int OPASIGNMULT = 45;
  public static final int STRING = 8;
  public static final int DOWNTO = 5;
  public static final int FALSE = 20;
  public static final int L_BRACKET = 48;
  public static final int OPGREATEREQ = 33;
  public static final int OPMULT = 40;
  public static final int STEP = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "NUM",
  "UPTO",
  "DOWNTO",
  "STEP",
  "VARIABLE",
  "STRING",
  "CONSTSTRING",
  "INTEGER",
  "CHARACTER",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "VOID",
  "TRUE",
  "FALSE",
  "BREAK",
  "NULL",
  "INPUT",
  "OUTPUT",
  "SWITCH",
  "CASE",
  "OPTION",
  "DEFAULT",
  "ID",
  "OPCOMP",
  "OPDIF",
  "OPGREATER",
  "OPGREATEREQ",
  "OPLESS",
  "OPLESSEQ",
  "OPCOND",
  "OPOR",
  "OPAND",
  "OPMOD",
  "OPMULT",
  "OPSUM",
  "OPINC",
  "OPASIGN",
  "OPASIGNADD",
  "OPASIGNMULT",
  "L_KEY",
  "R_KEY",
  "L_BRACKET",
  "R_BRACKET",
  "L_PAR",
  "R_PAR",
  "COMMA",
  "SEMICOLON",
  "COLON"
  };
}

