
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package nachts;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FUNCTION = 2;
  public static final int L_KEY = 44;
  public static final int OPSUM = 39;
  public static final int OUTPUT = 28;
  public static final int INPUT = 27;
  public static final int CASE = 30;
  public static final int INTEGER = 14;
  public static final int R_PAR = 49;
  public static final int FOR = 20;
  public static final int CHARACTER = 15;
  public static final int SEMICOLON = 51;
  public static final int OPASIGN = 41;
  public static final int OPTION = 31;
  public static final int COMMA = 50;
  public static final int UPTO = 4;
  public static final int OPREL = 34;
  public static final int R_KEY = 45;
  public static final int NUM = 3;
  public static final int MAIN = 55;
  public static final int IF = 17;
  public static final int DOT = 54;
  public static final int ID = 33;
  public static final int CONSTSTRING = 12;
  public static final int R_BRACKET = 47;
  public static final int BOOLEAN = 16;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int FLOAT_VAL = 11;
  public static final int NULL = 26;
  public static final int OPASIGNADD = 42;
  public static final int OPINC = 40;
  public static final int BREAK = 25;
  public static final int VOID = 22;
  public static final int SWITCH = 29;
  public static final int COLON = 52;
  public static final int ELSE = 18;
  public static final int VARIABLE = 7;
  public static final int WHILE = 19;
  public static final int DEFAULT = 32;
  public static final int FLOAT = 10;
  public static final int OPMOD = 37;
  public static final int L_PAR = 48;
  public static final int OPASIGNMULT = 43;
  public static final int STRING = 8;
  public static final int CONSTCHAR = 13;
  public static final int OPLOG = 36;
  public static final int DOWNTO = 5;
  public static final int AT = 53;
  public static final int FALSE = 24;
  public static final int L_BRACKET = 46;
  public static final int OPNEG = 35;
  public static final int OPMULT = 38;
  public static final int ELIF = 9;
  public static final int STEP = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "NUM",
  "UPTO",
  "DOWNTO",
  "STEP",
  "VARIABLE",
  "STRING",
  "ELIF",
  "FLOAT",
  "FLOAT_VAL",
  "CONSTSTRING",
  "CONSTCHAR",
  "INTEGER",
  "CHARACTER",
  "BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "VOID",
  "TRUE",
  "FALSE",
  "BREAK",
  "NULL",
  "INPUT",
  "OUTPUT",
  "SWITCH",
  "CASE",
  "OPTION",
  "DEFAULT",
  "ID",
  "OPREL",
  "OPNEG",
  "OPLOG",
  "OPMOD",
  "OPMULT",
  "OPSUM",
  "OPINC",
  "OPASIGN",
  "OPASIGNADD",
  "OPASIGNMULT",
  "L_KEY",
  "R_KEY",
  "L_BRACKET",
  "R_BRACKET",
  "L_PAR",
  "R_PAR",
  "COMMA",
  "SEMICOLON",
  "COLON",
  "AT",
  "DOT",
  "MAIN"
  };
}

